def wild_cats():
    wcats = {'Tiger':['Panthera Tigris','Asia, Southeast Asia, Russia, Indonesia','forest, Jungle, woodland, Swamp, grassland, Savanna','13 feet','120 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Bengal_tiger_%28Panthera_tigris_tigris%29_female_3_crop.jpg/330px-Bengal_tiger_%28Panthera_tigris_tigris%29_female_3_crop.jpg'],
'Lion':['Panthera leo','Africa, India','Grasslands, Savanna, Open Woodland, Dense Scrub','10 feet','120 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Lion_waiting_in_Namibia.jpg/330px-Lion_waiting_in_Namibia.jpg'],
'Jaguar':['Panthera Onca','North America, Central America, South America','Swamp, grassland, Arid Scrubland, Tropical Forest','6.25 feet','76 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Jaguar_%28Panthera_onca_palustris%29_male_Three_Brothers_River_2.jpg/330px-Jaguar_%28Panthera_onca_palustris%29_male_Three_Brothers_River_2.jpg'],
'Cheetah':['Acynonix Jubatus','Northern Africa, Southern Africa, Eastern Africa, The Sahel','Open Plains, Desert, Dry Forests, Grasslands','7.5 feet','90 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Cheetah_Kruger.jpg/330px-Cheetah_Kruger.jpg'],
'Leopard':['Panthera Pardus','Southeast Asia, South Asia, Africa, India, Middle East','Rainforest, Desert, Woodland, Grassland, Savanna','7.2 feet','70 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Nagarhole_Kabini_Karnataka_India%2C_Leopard_September_2013.jpg/330px-Nagarhole_Kabini_Karnataka_India%2C_Leopard_September_2013.jpg'],
'Lynx':['Lynx Canadensis','North America, Russia, Europe, Central Asia, Himalayas, Iberia','Tundra, Forests, Semi-Deserts','4.25 feet','70 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Lynx_pardinus.png/330px-Lynx_pardinus.png'],
'Margay':['Leopardus Wiedii','South America, Central America','Forest, Tropical Evergreen, Humid Forests','3.5 feet','60.96 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Margay.jpg/330px-Margay.jpg'],
'Cougar':['Puma Concolor','Western North America, Florida, South America','Tropical Forest, Swamp, Grassland, Desert Scrub','9 feet','90 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Puma_face.jpg/330px-Puma_face.jpg'],
'Bobcat':['Lynx Rufus','North America','Mountain, Woodland, desert, Forest, Swampland','4.16667 feet','53.34 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Bobcat2.jpg/330px-Bobcat2.jpg'],
'Snow Lepoard':['Panthera Uncia','Central Asia, Himalayas, Russia','Mountain','6.88976 feet','1524 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Snow_leopard_in_Afghanistan.jpg/330px-Snow_leopard_in_Afghanistan.jpg'],
'Clouded Lepoard':['Neofelis Nebulosa','Southeast Asia, Himalayas','Mountain, Rainforest, Swamp, Dry Forest','2.95276 feet','55 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/CloudedLeopard.jpg/330px-CloudedLeopard.jpg'],
'Siberian Tiger':['Panthera Tigris Altaica','Korea, China, South Siberia','Birch Forest','11 feet','106.68 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/P.t.altaica_Tomak_Male.jpg/330px-P.t.altaica_Tomak_Male.jpg'],
'Ocelot':['Leopardus Pardalis','Texas, Mexico, Central America, South America','Forest, Grassland, Marsh','2.91667 feet','50.8 cm','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Ocelot_%28Jaguatirica%29_Zoo_Itatiba.jpg/330px-Ocelot_%28Jaguatirica%29_Zoo_Itatiba.jpg']
}
    return wcats